Location:
  _class: dtrpg.core.map.Location
  travel_actions: [ TravelAction ]

TravelAction:
  _class: dtrpg.core.map.TravelAction
  required to: Location

PlayerFactory:
  _class: dtrpg.core.player.PlayerFactory
  required default_location: Location
  optional resource_factories: [ ResourceFactory ]

Player:
  _class: dtrpg.core.player.Player

ResourceFactory:
  _class: dtrpg.core.player.ResourceFactory
  required id: str
  optional initial: int
  optional max: int
  optional base_gen_rate: float
  optional clock: Clock

Resource:
  _class: dtrpg.core.player.Resource

Config:
  _class: dtrpg.core.Config
  required player_factory: PlayerFactory

TravelEvent:
  _class: dtrpg.core.map.TravelEvent

Clock:
  _class: dtrpg.core.Clock
  optional base: int
