Location:
  _class: dtrpg.core.map.Location
  travel_actions: [ TravelAction ]

TravelAction:
  _class: dtrpg.core.map.TravelAction
  required to: Location

PlayerFactory:
  _class: dtrpg.core.player.PlayerFactory
  required default_location: Location

Config:
  _class: dtrpg.core.Config
  required player_factory: PlayerFactory

TravelEvent:
  _class: dtrpg.core.map.TravelEvent
