Location:
  _class: dtrpg.core.map.Location
  travel_actions: [ TravelAction ]
  optional local_actions: [ Action ]

Action:
  _class: dtrpg.core.action.Action
  _abstract: True
  optional costs: [ ResourceCost ]

ResourceChangesAction:
  _class: dtrpg.core.action.ResourceChangesAction
  _base: Action
  required resource_changes: [ ResourceChange ]

ResourceChangeEvent:
  _class: dtrpg.core.action.ResourceChangeEvent

ItemReceiveAction:
  _class: dtrpg.core.action.ItemReceiveAction
  _base: Action
  required item_factory: ItemStackFactory

ItemReceivedEvent:
  _class: dtrpg.core.action.ItemReceivedEvent

TravelAction:
  _class: dtrpg.core.map.TravelAction
  _base: Action
  required to: Location

PlayerFactory:
  _class: dtrpg.core.player.PlayerFactory
  required default_location: Location
  required container_factory: ContainerFactory
  optional resource_factories: [ ResourceFactory ]

Player:
  _class: dtrpg.core.player.Player

Container:
  _class: dtrpg.core.item.Container

ContainerFactory:
  _class: dtrpg.core.item.ContainerFactory
  required max_items: int

Item:
  _class: dtrpg.core.item.Item
  optional max_stack: int

ItemStackFactory:
  _class: dtrpg.core.item.ItemStackFactory
  required item: Item
  optional stack: int

ResourceFactory:
  _class: dtrpg.core.player.ResourceFactory
  required id: str
  optional initial: int
  optional max: int
  optional base_gen_rate: float
  optional clock: Clock

Resource:
  _class: dtrpg.core.player.Resource

ResourceChange:
  _class: dtrpg.core.player.ResourceChange
  required id: str
  required value: int

ResourceCost:
  _class: dtrpg.core.player.ResourceCost
  required id: str
  required cost: int

Config:
  _class: dtrpg.core.Config
  required player_factory: PlayerFactory

TravelEvent:
  _class: dtrpg.core.map.TravelEvent

Clock:
  _class: dtrpg.core.Clock
  optional base: int
