Config config:
  player_factory: player_factory

Clock clock:
  base: 3600

ProportionalTester default_tester: {}

# some useful, universal objects:

FreeSpaceRequirement free_space_req: {}

InfoEvent dialogue_invalid_action_event: {}
